FROM docker.io/library/golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /client ./cmd/client

FROM docker.io/library/alpine:3.19
COPY --from=builder /client /client
ENTRYPOINT ["/client"]
